server:
 port: 80
 context-path: /
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_book
  username: root
  password: zhujn
 jpa:
 hibernate:
  ddl-auto: update
  show-sql: true